version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 8jJ8cC8gVEqtVJs7ntkw
      MYSQL_DATABASE: bzif0dgvzjp0ltbihfzv
      MYSQL_USER: uobhlq41ybfzh4h3
    ports:
    - "3310:3306"

  nodejs:
    build:
      context: .
    ports:
      - "3306:3306"
    depends_on:
      - mysql
