version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - HOST=mysqldb
      - USER=$DB_USER
      - PASSWORD=$DB_PASSWORD
      - NAME=$DB_NAME
      - PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true